# This workflow action is not included in the template.
# This action syncs all changes from this repo to the Scaffoldly Template
# as a pull request, so we can internally develop templates and have them
# pushed back to the original template

name: Scaffoldly Template Sync
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Live Deploy"]
    types:
      - completed
env:
  SCAFFOLDLY_GITHUB_TOKEN: ${{ secrets.SCAFFOLDLY_TEMPLATE_SYNC_GITHUB_TOKEN }}
  SCAFFOLDLY_TARGET_REPO: scaffoldly/web-jwt-verifier-template
  VERSION_FILE: package.json
jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      OLD_VERSION: ${{ steps.prepare.outputs.OLD_VERSION }}
      NEW_VERSION: ${{ steps.prepare.outputs.NEW_VERSION }}
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - id: prepare
        run: |
          old_version=$(jq -r .version ${{ env.VERSION_FILE }})
          new_version=$(npx semver -i minor $old_version)
          echo "Old version is ${old_version}"
          echo "New version is ${new_version}"
          echo "::set-output name=OLD_VERSION::${old_version}"
          echo "::set-output name=NEW_VERSION::${new_version}"
  create-pr:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/checkout@v2
        with:
          token: ${{ env.SCAFFOLDLY_GITHUB_TOKEN }}
          repository: ${{ env.SCAFFOLDLY_TARGET_REPO }}
          ref: main
          persist-credentials: false
          fetch-depth: 0
          path: .scaffoldly/template
      - run: |
          rm -fr .git
          cp -R .scaffoldly/template/.git .
          rm -fr .scaffoldly/template
      - run: |
          git add .
          git restore -s@ -SW -- .scaffoldly
          git restore -s@ -SW -- .github/workflows/slyci-*
          git status
          git diff --staged
      - run: |
          contents="$(jq -r --arg v ${{ needs.prepare.outputs.NEW_VERSION }} '.version = $v' ${{ env.VERSION_FILE }})"
          echo "${contents}" > ${{ env.VERSION_FILE }}
          git add ${{ env.VERSION_FILE }}
      - uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ env.SCAFFOLDLY_GITHUB_TOKEN }}
          branch: "${{ github.repository }}/${{ needs.prepare.outputs.OLD_VERSION }}"
          base: main
          title: "${{ needs.prepare.outputs.NEW_VERSION }}: Sync ${{ needs.prepare.outputs.OLD_VERSION }} from ${{ github.repository }}"
          commit-message: "Update to ${{ needs.prepare.outputs.NEW_VERSION }}"
          body: "Automated sync of ${{ github.repository }}@${{ needs.prepare.outputs.OLD_VERSION }}"
          assignees: cnuss # TODO: Codeowners
  bump-version:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          ref: main
          persist-credentials: false
          fetch-depth: 0
          path: .scaffoldly/main
      - run: |
          current_version=$(jq -r .version ${{ env.VERSION_FILE }})
          desired_version=$(npx semver $current_version ${{ needs.prepare.outputs.NEW_VERSION }} | tail -1)
          echo "Current version is ${current_version}"
          echo "Desired version is ${desired_version}"
          echo "CURRENT_VERSION=${current_version}" >> $GITHUB_ENV
          echo "DESIRED_VERSION=${desired_version}" >> $GITHUB_ENV
        working-directory: .scaffoldly/main
      - if: ${{ env.CURRENT_VERSION < env.DESIRED_VERSION }}
        run: |
          git config --local user.email "github-action@users.noreply.github.com"
          git config --local user.name "GitHub Action"
          contents="$(jq -r --arg v ${{ env.DESIRED_VERSION }} '.version = $v' ${{ env.VERSION_FILE }})"
          echo "${contents}" > ${{ env.VERSION_FILE }}
          git add ${{ env.VERSION_FILE }}
          git commit -m "CI: Bump to ${{ env.DESIRED_VERSION }}"
        working-directory: .scaffoldly/main
      - if: ${{ env.CURRENT_VERSION < env.DESIRED_VERSION }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          branch: main
          directory: ".scaffoldly/main"